# Generated by Django 3.2 on 2021-04-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpis_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maoni',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
