# Generated by Django 3.2 on 2021-04-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpis_backend', '0002_maoni_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maoni',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
