# Generated by Django 3.2 on 2021-04-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpis_backend', '0003_alter_maoni_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maoni',
            options={'verbose_name_plural': 'maoni'},
        ),
        migrations.AddField(
            model_name='maoni',
            name='category',
            field=models.CharField(choices=[('maoni', 'maoni'), ('mapendekezo', 'mapendekezo'), ('pongezi', 'pongezi')], default='empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='maoni',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
